# Site settings
title: Smokey Hollow Farm
description: A high-end horse boarding and training farm in Jamesville, NY.
url: "https://shf-alh.com"  # Your domain
baseurl: ""
permalink: pretty  # Clean URLs like /schedule

# SEO and site settings
author: Alexa Harris
email: farmerjoblue@aol.com
defaults:
  - scope:
      path: ""
    values:
      layout: default
      image: /assets/images/og-image.jpg  # Default Open Graph image (upload a representative farm photo as og-image.jpg in assets/images for social sharing)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag  # Added for enhanced SEO: auto-generates meta tags, Open Graph, Twitter Cards, and JSON-LD

# Business details for SEO structured data (JSON-LD LocalBusiness schema)
address:
  street: "Your Street Address, Jamesville, NY 13078"  # Replace with actual address
  phone: "(315) 123-4567"  # Replace with actual phone
  coordinates:
    lat: 42.9912  # Approximate lat/long for Jamesville, NY; replace with precise values
    long: -76.0633

# Navigation menu (add/remove pages here)
navigation:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Facilities
    url: /facilities
  - title: Gallery
    url: /gallery
  - title: Alumni
    url: /alumni
  - title: Schedule
    url: /schedule
  - title: Contact
    url: /contact

# Exclude from processing (for performance)
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Performance optimizations: Enable compression if using GitHub Pages with custom build
compress_html:
  clippings: all
  endings: all

social:
  facebook: "https://www.facebook.com/smokeyhollowfarmalh/"
  instagram: "https://www.instagram.com/smokeyhollowfarm/"

address:
  street: "4372 Old Barker Hill Rd,"